In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row 5 columns

array([[1, 2, 3, 4, 5]])

In [10]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [12]:
arr2=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr2)


[[1 2 3 4 5]
 [5 6 7 8 9]]


In [17]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
##Atrributes of numpy
arr=np.array([[1,2,3],[4,5,6]])
print("Array;\n",arr)
print("Shape;",arr.shape)
print("number of dimensions;",arr.ndim)
print("size (number of elements)",arr.size)
print("Dta tye;",arr.dtype)
print("item size (in bytes);",arr.itemsize)

Array;
 [[1 2 3]
 [4 5 6]]
Shape; (2, 3)
number of dimensions; 2
size (number of elements) 6
Dta tye; int64
item size (in bytes); 8


In [21]:
##numoy vectorized oerataions
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([10,20,30,40,50,60])

print("addition;",arr1+arr2)

print("subratction",arr1-arr2)

print("Multilication",arr1*arr2)

print("Division",arr1/arr2)

addition; [11 22 33 44 55 66]
subratction [ -9 -18 -27 -36 -45 -54]
Multilication [ 10  40  90 160 250 360]
Division [0.1 0.1 0.1 0.1 0.1 0.1]


In [22]:
#Universal function
arr=np.array([2,3,4,5,6])
##sq root
print(np.sqrt(arr))
#exonential
print(np.exp(arr))
##sine
print(np.sin(arr))
##log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [24]:
##Universal functions
##array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array; \n",arr)

array; 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
arr[2][1]

np.int64(10)

In [30]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])