In [4]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row 5 columns

array([[1, 2, 3, 4, 5]])

In [6]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [7]:
arr2=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr2)


[[1 2 3 4 5]
 [5 6 7 8 9]]


In [8]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
##Atrributes of numpy
arr=np.array([[1,2,3],[4,5,6]])
print("Array;\n",arr)
print("Shape;",arr.shape)
print("number of dimensions;",arr.ndim)
print("size (number of elements)",arr.size)
print("Dta tye;",arr.dtype)
print("item size (in bytes);",arr.itemsize)

Array;
 [[1 2 3]
 [4 5 6]]
Shape; (2, 3)
number of dimensions; 2
size (number of elements) 6
Dta tye; int64
item size (in bytes); 8


In [12]:
##numoy vectorized oerataions
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([10,20,30,40,50,60])

print("addition;",arr1+arr2)

print("subratction",arr1-arr2)

print("Multilication",arr1*arr2)

print("Division",arr1/arr2)

addition; [11 22 33 44 55 66]
subratction [ -9 -18 -27 -36 -45 -54]
Multilication [ 10  40  90 160 250 360]
Division [0.1 0.1 0.1 0.1 0.1 0.1]


In [13]:
#Universal function
arr=np.array([2,3,4,5,6])
##sq root
print(np.sqrt(arr))
#exonential
print(np.exp(arr))
##sine
print(np.sin(arr))
##log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [14]:
##Universal functions
##array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array; \n",arr)

array; 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print(arr[2][1])

10


In [16]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
print(arr[0][0])
print(arr[0:2,1:])

1
[[2 3 4]
 [6 7 8]]


In [ ]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [25]:
arr[1:,1]

array([ 6, 10])

In [31]:
arr[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [40]:
##modify
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [41]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [46]:
### statistical concepts Normalization
data=np.array([1,2,3,4,5,6,7,8,9,10])

mean=np.mean(data)
print("mean",mean)
median=np.median(data)
print("median",median)
std_dev=np.std(data)
print("st dev",std_dev)
varian=np.var(data)
print("variance  ",varian)

mean 5.5
median 5.5
st dev 2.8722813232690143
variance   8.25


In [50]:
data=np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>5) & (data<=8)]

array([6, 7, 8])